[package]
name = "dyn_trie"
version = "1.0.0"
edition = "2021"
keywords = [ "digital-tree", "prefix-tree", "trie", "retrieval-tree" ]
authors = [ "software9119.technology" ]
description = "Dynamic trie is trie capable of mapping any T to any string."
homepage = "https://github.com/bravequickcleverfibreyarn/tries"
repository = "https://github.com/bravequickcleverfibreyarn/tries"
license = "MIT"
categories = [ "data-structures" ]
